#!/usr/bin/env sh

if [ `which node` ]; then
  echo "Primeiro, remova a instalação do node de sua máquina com o comando:"
  echo
  echo " $ apt purge nodejs"
  echo
  exit 1
fi

sudo curl -s https://raw.githubusercontent.com/flavioarcega/utils/master/bash/update-node-alternatives -o /usr/local/bin/update-node-alternatives && sudo chmod +x /usr/local/bin/update-node-alternatives

echo "Utilitário instalado com sucesso!"
echo "Execute o comando abaixo para maiores informações:"
echo
echo " $ update-node-alternatives -h"
echo
