#!/bin/sh

####################################################
# utilitario para manipulação de alternatives node #
####################################################

BIN=/usr/bin
LIB=/usr/lib/node

die() { printf "$*\n" >&2; exit 1; }

validarLib() {
  if [ ! -d /usr/lib/node/$1 ]; then
    die "$LIB/$1 não encontrado."
  fi
}

case "$1" in
  -i)
      if [ -z "$2" ] || [ -z "$3" ]; then
      die "Syntax: -i {versao} {prioridade}"
      fi
      if [ ! -d $LIB ]; then
        mkdir -p $LIB
      fi
      cd $LIB
      curl -s https://nodejs.org/dist/$2/node-$2-linux-x64.tar.xz | tar -xaJ > /dev/null 2>&1
      if [ $? != 0 ]; then
      die "Versão não encontrada no site do projeto!\n * https://nodejs.org/dist/$2/node-$2-linux-x64.tar.xz"
      fi
      mv node-$2-linux-x64 $2
      validarLib $2
      update-alternatives --install $BIN/node node $LIB/$2/bin/node $3 \
                            --slave $BIN/npm  npm  $LIB/$2/bin/npm  \
                            --slave $BIN/npx  npx  $LIB/$2/bin/npx
      ;;
  -r)
      if [ -z "$2" ]; then
      die "Syntax: -r {versao}"
      fi
      validarLib $2
      update-alternatives --remove  node $LIB/$2/bin/node
      ;;
  -l) 
      update-alternatives --list node
      ;;
  -h)
      echo "Utilitário para instalação de alternatives node."
      echo
      echo "Parâmetros:"
      echo "  -i - instalar um alternative"
      echo "  -r - remover um alternative"
      echo "  -l - listar os alternatives instalados"
      ;;
  *)
      echo "Utilitário para instalação de alternatives node."
      echo
      echo "Parâmetros:"
      echo "  -i {versao} {prioridade}"
      echo "  -r {versao}"
      echo "  -l"
      echo "  -h"
esac
