#!/bin/sh

####################################################
# utilitario para manipulação de alternatives node #
####################################################

BIN=/usr/bin
LIB=/usr/lib/node

die() { printf "$*\n" >&2; exit 1; }

validarLib() {
  if [ ! -d /usr/lib/node/$1 ]; then
    die "$LIB/$1 não encontrado."
  fi
}

updateExes() {
  prioridade=1000
  update-alternatives --remove-all node 2>&1 > /dev/null
  MENSAGEM="Executáveis encontrados"
  for dir in /usr/lib/node/*
  do
    SLAVES=""
    MENSAGEM="$MENSAGEM\n  $(basename $dir):"
    for bin in $(find $dir/bin -type f,l -executable)
    do
      MENSAGEM="$MENSAGEM $(basename $bin)"
      if [ "$(basename $bin)" != "node" ]; then
        SLAVES="--slave /usr/bin/$(basename $bin) $(basename $bin) $bin $SLAVES"
      fi
    done
    prioridade=`echo "$prioridade + 10" | bc`
    update-alternatives --install /usr/bin/node node $dir/bin/node $prioridade $SLAVES 2>&1 > /dev/null
  done
	chown -R root:root /usr/lib/node
	chmod -R a+r /usr/lib/node/*
  echo $MENSAGEM
}

if [ "$(id -u)" != "0" ]; then
    echo "É preciso sudo ou root para executar esse script."
    exit 1
fi

case "$1" in
  -i)
      if [ -z "$2" ]; then
      die "Syntax: -i {versao}"
      fi
      if [ ! -d $LIB ]; then
        mkdir -p $LIB
      fi
      cd $LIB
      curl -s https://nodejs.org/dist/$2/node-$2-linux-x64.tar.xz | tar -xaJ > /dev/null 2>&1
      if [ $? != 0 ]; then
      die "Versão não encontrada no site do projeto!\n * https://nodejs.org/dist/$2/node-$2-linux-x64.tar.xz"
      fi
      mv node-$2-linux-x64 $2
      validarLib $2
      updateExes 
      ;;
  -r)
      if [ -z "$2" ]
      then
        die "Syntax: -r {versao}"
      fi
      validarLib $2
      updateExes
      ;;
  -u)
      updateExes 
      ;;
  -l) 
      update-alternatives --list node
      ;;
  -h)
      echo "Utilitário para instalação de alternatives node."
      echo
      echo "Parâmetros:"
      echo "  -i - instalar uma versão do node"
      echo "  -r - remover uma versão do node"
      echo "  -u - atualizar executáveis node (update)"
      echo "  -l - listar os alternatives instalados"
      ;;
  *)
      echo "Utilitário para instalação de alternatives node."
      echo "-h para acessar a ajuda"
esac
